-- ==============================================================================
-- Supabase SQL Schema Migration Script
-- Adds business_name and website_url columns to the quiz_submissions table
-- ==============================================================================

-- 1. Alter existing table to add new columns for Quiz 3 (Brand Diagnostic)
ALTER TABLE IF EXISTS quiz_submissions 
ADD COLUMN IF NOT EXISTS business_name TEXT,
ADD COLUMN IF NOT EXISTS website_url TEXT;

-- 2. Add helpful column documentation
COMMENT ON COLUMN quiz_submissions.business_name IS 'Business Name submitted from Brand Diagnostic Quiz';
COMMENT ON COLUMN quiz_submissions.website_url IS 'Website URL submitted from Brand Diagnostic Quiz';

-- ==============================================================================
-- (Optional) Complete table creation script for new environments
-- ==============================================================================
CREATE TABLE IF NOT EXISTS quiz_submissions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name TEXT,
  last_name TEXT,
  email TEXT,
  phone TEXT,
  business_name TEXT,
  website_url TEXT,
  score INTEGER,
  answers JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
